
#
# default: &default
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: demetri-portfolio_development
  pool: 5
  username: kaylamorrison
  password:

  # <<: *default
  # database: db/development.sqlite3

test:
  adapter: postgresql
  encoding: unicode
  database: demetri-portfolio_test
  pool: 5
  username: kaylamorrison
  password:
  # <<: *default
  # database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: demetri-portfolio_production
  pool: 5
  username: kaylamorrison
  password:
  # <<: *default
  # database: db/production.sqlite3
